### ISSUE TITLE
Questions for 19/02

### ISSUE THREAD

**Issue by Reloxed** [Reloxed/DT2Group14#5]
- How can we check that a collection has only URLs in persistence?
- Which is the pattern? (A que se refiere Felix aqui?)
- Which ticker should we use? The one in requirement 3 or the one in requirement 17?

**Comment by Reloxed** [comment]
- Change endMoment in Enrolment to optional.
- The ticker we will use for procession is 5 X's, but if in any case we come across another ticker, we will use the one with 6 X's.

**Comment by MarioBG** [comment]
For URL collection validation, check out https://github.com/jirutka/validator-collection - it was used with moderate success in our 1st term deliverables

**Comment by Reloxed** [comment]
Feedback about Hackathon:
- It's better to make a competition, like some company makes a proposal, students apply for it and then they get the contract, for example. The company can contact the professor for feedback.
- A class is missing in order to see how the workers check a deliverable.
- Change the name of the project 👍 
- We have to make it more complex. Maybe something related to the planning, developing the practice contract.
